.. autoclass:: pybricks.hubs.CityHub
    :no-members:

    Usage of each built-in device is described below.

    .. rubric:: Using the hub status light

    .. automethod:: pybricks.hubs::CityHub.light.on

    .. automethod:: pybricks.hubs::CityHub.light.off

    .. rubric:: Using the battery

    .. automethod:: pybricks.hubs::CityHub.battery.voltage

    .. automethod:: pybricks.hubs::CityHub.battery.current

