.. autoclass:: pybricks.hubs.CityHub
    :no-members:

    .. rubric:: Motor and Sensor Ports

    .. data:: Port.A
    .. data:: Port.B

    Usage of each built-in device is described below.

    .. rubric:: Using the hub status light

    .. automethod:: pybricks._instances.light.on

    .. automethod:: pybricks._instances.light.off

    .. rubric:: Using the battery

    .. automethod:: pybricks._instances.battery.voltage

    .. automethod:: pybricks._instances.battery.current
