.. autoclass:: pybricks.hubs.MoveHub
    :no-members:

    .. rubric:: Motor and Sensor Ports

    +-----------------+-----------------+-----------------+-----------------+
    |.. data:: Port.A |.. data:: Port.B |.. data:: Port.C |.. data:: Port.D |
    +-----------------+-----------------+-----------------+-----------------+

    .. rubric:: Using the hub status light

    .. automethod:: pybricks._instances.light.on

    .. automethod:: pybricks._instances.light.off

    .. rubric:: Using the battery

    .. automethod:: pybricks._instances.battery.voltage

    .. automethod:: pybricks._instances.battery.current
