# SPDX-License-Identifier: MIT
# Copyright (c) 2020-2021 The Pybricks Authors

from typing import Collection, Optional, Tuple

class Matrix:
    def __init__(self, rows: Collection[Collection[int]]): ...
    @property
    def T(self) -> Matrix: ...
    @property
    def shape(self) -> Tuple[int, int]: ...

    def __add__(self, other) -> Matrix: ...
    def __iadd__(self, other) -> Matrix: ...
    def __sub__(self, other) -> Matrix: ...
    def __isub__(self, other) -> Matrix: ...
    def __mul__(self, other) -> Matrix: ...
    def __rmul__(self, other) -> Matrix: ...
    def __imul__(self, other) -> Matrix: ...
    def __truediv__(self, other) -> Matrix: ...
    def __itruediv__(self, other) -> Matrix: ...
    def __floordiv__(self, other) -> Matrix: ...
    def __ifloordiv__(self, other) -> Matrix: ...

def vector(x: float, y: float, z: Optional[float] = None) -> Matrix: ...

class Axis:
    X: Matrix
    Y: Matrix
    Z: Matrix
