# SPDX-License-Identifier: MIT
# Copyright (c) 2020-2022 The Pybricks Authors

from typing import Collection, List, Optional, Tuple, Union

from ._common import (
    Keypad,
    DCMotor as _DCMotor,
    ColorLight,
    LightArray,
    Motor as _Motor,
    Light as BaseLight,
)

from .parameters import Color, Port

class UltrasonicSensor:
    lights: LightArray
    def __init__(self, port: Port): ...
    def distance(self) -> int: ...
    def presence(self) -> bool: ...

class ForceSensor:
    def __init__(self, port: Port): ...
    def force(self) -> int: ...
    def distance(self) -> int: ...
    def pressed(self, force: int = 3) -> bool: ...
    def touched(self) -> bool: ...

class ColorLightMatrix:
    def __init__(self, port: Port) -> None: ...
    def on(self, color: Union[Color, List[Color]]) -> None: ...
    def off(self) -> None: ...

class InfraredSensor:
    def __init__(self, port: Port): ...
    def reflection(self) -> int: ...
    def distance(self) -> int: ...
    def count(self) -> int: ...

class Light(BaseLight):
    def __init__(self, port: Port): ...
