name: Build Python package and docs

on: push

jobs:
  build:

    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        pipx install poetry
        poetry install
    - name: Lint Python code
      run: poetry run ruff check
    - name: Check Python formatting
      run: poetry run ruff format --check
    - name: Build package
      run: poetry build
    - name: Lint docs
      run: poetry run doc8
    - name: Build html docs for Read the Docs
      run: poetry run make -C doc html
    - name: Build html docs for Pybricks Code IDE
      run: poetry run make -C doc html TAG=ide
