name: pybricks_jedi

on: [push, pull_request]

jobs:
  test:
    if: github.ref_type != 'tag'
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v6
    - run: pipx install poetry
    - run: poetry install
      working-directory: ./jedi
    - run: poetry run pytest -vv
      working-directory: ./jedi
