name: Release @pybricks/jedi

on:
  push:
    tags:
    - 'v4.*'

jobs:
  publish_jedi:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v6
    - name: Get version from tag
      run: |
        VERSION="${GITHUB_REF_NAME#v}"
        NPM_VERSION=$(echo "$VERSION" | sed 's/\([0-9]\)a\([0-9]\)/\1-alpha.\2/;s/\([0-9]\)b\([0-9]\)/\1-beta.\2/;s/\([0-9]\)rc\([0-9]\)/\1-rc.\2/')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "NPM_VERSION=$NPM_VERSION" >> $GITHUB_ENV
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install poetry
      run: pipx install poetry
    - name: Set pybricks-jedi version
      run: poetry version "$VERSION"
      working-directory: jedi
    - uses: actions/setup-node@v6
      with:
        node-version: '22.x'
        registry-url: 'https://registry.npmjs.org'
    - run: ./build.py "$NPM_VERSION"
      working-directory: npm/jedi
    - run: npm publish
      working-directory: npm/jedi/build
